export const Experience = [
    {
        App : "Fonicris",
        Descripcion : "App to manage assets",
        Categoria : "Work Experiences",
        tecnologias : [
            "Mobile", "C#", "XAML", ".NET" , "MAUI", "Google Console" 
        ],
        badge : false,
        BadgeText : 'Reciente',
        BadgeColor : ' ',
        hasWebLink : false,
        webLink : '',
        hasGithubLink : false,
        githubLink : '',
        img : '/appsShowcase/Fonicris.jpg',
        statusColor : 'bg-white',
        statusIcon: 'black',
    },
    {
        App : "Technician",
        Descripcion : "App to manage clients",
        Categoria : "Work Experiences",
        tecnologias : [
            "Mobile", "C#", "XAML", ".NET" , "SQLite"
        ],
        badge : false,
        BadgeText : 'Reciente',
        BadgeColor : ' ',
        hasWebLink : false,
        webLink : '',
        hasGithubLink : true,
        githubLink : 'https://github.com/anthoni/technician-app',
        img : '/appsShowcase/Technician.jpg',
        statusColor : 'bg-[#f4f4f4]',
        statusIcon: 'black',
    },
    {
        App : "Unitasks",
        Descripcion : "University app for managing classes and subjects",
        Categoria : "Personal Experiences",
        tecnologias : [
            "Mobile", "C#", "XAML", ".NET" , "MAUI" , "SQLite", "React"
        ],
        badge : false,
        BadgeText : 'Reciente',
        BadgeColor : ' ',
        hasWebLink : false,
        webLink : '',
        hasGithubLink : true,
        githubLink : 'https://github.com/anthoni/unitasks',
        img : '/appsShowcase/Unitasks.jpg',
        statusColor : 'bg-white',
        statusIcon: 'black',
    },
    {
        App : "PerfectSounds",
        Descripcion : "Music app for scales and notes",
        Categoria : "Personal Experiences",
        tecnologias : [
            "Mobile", "C#", "XAML", ".NET", "MAUI"
        ],
        badge : false,
        BadgeText : 'Reciente',
        BadgeColor : ' ',
        hasWebLink : false,
        webLink : '',
        hasGithubLink : true,
        githubLink : 'https://github.com/anthoni/perfect-sounds',
        img : '/appsShowcase/PerfectSounds.jpg',
        statusColor : 'bg-[#2E2E36]',
        statusIcon: 'white',
    },
]

export const PCExperience = [
    {
        App : "FonicrisPC",
        Descripcion : "Desktop app to manage assets with advanced features",
        Categoria : "Work Experiences",
        tecnologias : ["PC","C#", "XAML", ".NET", "WPF", "Google Console"],
        badge : false,
        BadgeText : 'Reciente',
        BadgeColor : ' ',
        hasWebLink : true,
        webLink : 'https://fonicris.versatile.do',
        hasGithubLink : false,
        githubLink : '',
        img : '/appsShowcase/FonicrisPC.png',
    },
]

export const LandingExperience = [
    {
        App: "OWEN | Trio Latin-Pop",
        Descripcion: "Landing page moderna para banda musical latina pop dominico-venezolana con carrusel interactivo, galería de equipo, integración de redes sociales y optimización SEO",
        Categoria: "Landing Pages",
        tecnologias: ["ASTRO", "HTML", "TAILWIND CSS", "TYPESCRIPT", "VERCEL"],
        badge: true,
        BadgeText: 'Reciente',
        BadgeColor: 'bg-gradient-to-r from-purple-500 to-blue-500',
        hasWebLink: true,
        webLink: 'https://owenmusic.vercel.app/',
        hasGithubLink: true,
        githubLink: 'https://github.com/AnthonyDev65/owen-landing',
        img: '/appsShowcase/owen.png',
    },
    {
        App: "UniTasks",
        Descripcion: "Plataforma social universitaria completa para estudiantes - conecta, comparte y organiza tu vida académica con grupos de estudio, eventos, sistema de amigos y notificaciones en tiempo real",
        Categoria: "Aplicaciones Web",
        tecnologias: ["React", "TypeScript", "Supabase", "Vite", "CSS"],
        badge: true,
        BadgeText: 'Nuevo',
        BadgeColor: 'bg-gradient-to-r from-blue-500 to-purple-600',
        hasWebLink: false,
        webLink: '',
        hasGithubLink: true,
        githubLink: 'https://github.com/AnthonyDev65/UNITASKS-REACT',
        img: '/appsShowcase/UnitasksWeb.png',
    },
    {
        App: "Fonicris",
        Descripcion: "Sistema integral de gestión de inventario desarrollado para orfanatos. Permite el control completo de activos con funcionalidades CRUD, sistema de roles (Prime, Admin, Editor, Visualizador), generación de códigos QR, carga de imágenes, dashboard con estadísticas, historial de actividades y gestión de usuarios. Integrado con Google Sheets como base de datos y Google Drive para almacenamiento de archivos.",
        Categoria: "Aplicaciones Web",
        tecnologias: ["React", "TypeScript", "Tailwind CSS", "Google Sheets API", "Google Drive API", "Zustand", "Recharts", "Vite"],
        badge: true,
        BadgeText: 'Reciente',
        BadgeColor: 'bg-green-500',
        hasWebLink: false,
        webLink: 'https://fonicris.versatile.do',
        hasGithubLink: true,
        githubLink: 'https://github.com/AnthonyDev65/Fonicris',
        img: '/appsShowcase/FonicrisWeb.png',
    }
]